#!/bin/bash

echo $BASH_VERSION


for ((i=$1; i<=$2; i++))
do
   echo "downloading PDF id: $i"
   curl -k -u `head -n1 .invfox-api-token` -J -O \
       "https://www.cebelca.biz/API-pdf?id=${i}&res=invoice-sent&lang=si&format=pdf&doctitle=Račun%20št."
done