#!/bin/bash

showUsage() {
    cat <<EOF
Usage: 
get-id 1 120
EOF
}

DOMAIN=`cat download.cfg | grep "^domain:" | cut -f2 -d:`
TOKEN=`head -n1 .invfox-api-token`
RESOURCE="$1"

if [ $# -eq 3 ]; then
    curl -s -k -u $TOKEN:x  --data-urlencode "docnum=$3" --data-urlencode "location=$2" "https://${DOMAIN}/API?_r=${RESOURCE}&_m=select-by-docnum&_f=csv" | head -n2 | tail -n1 | cut -f1 -d\;
else
    showUsage
fi
